### ISSUE TITLE
`True` vs `true` in the usage example, possible doc 🐛

### ISSUE THREAD

**Issue by jessebot** [matrix-org/synapse-s3-storage-provider#104]
In the usage example [here](https://github.com/matrix-org/synapse-s3-storage-provider#usage) it shows the following:

```yaml
  store_local: True
  store_remote: True
  store_synchronous: True
```

Should all of those `True` be `true` (lower case `t`) since yaml is weird like that? 🤷 Happy to submit a quick PR for that if needed. :)

Also thanks for working on this! I haven't gotten it working yet, but I am very excited to eventually get it working.

Final question while I'm at it: If I set `store_local` to `false` will it only store stuff in the s3 and skip the local volume all together? 🤔
