### ISSUE TITLE
How to configure max_pool_connections?

### ISSUE THREAD

**Issue by ajkessel** [matrix-org/synapse-s3-storage-provider#117]
package versions:
```
matrix-synapse==1.117.0
synapse-s3-storage-provider==1.5.0
```
storage.yaml:
```
media_storage_providers:
- module: s3_storage_provider.S3StorageProviderBackend
  store_local: True
  store_remote: True
  store_synchronous: True
  config:
    bucket: [redacted]
    region_name: us-east-1
    endpoint_url: [redacted]
    access_key_id: [redacted]
    secret_access_key: [redacted]
    storage_class: "STANDARD_IA"
    threadpool_size: 60
```
I frequently see this homeserver error and media fails to retrieve from S3:
```
2024-10-23 12:04:29,673 - urllib3.connectionpool - 329 - WARNING - GET-2519500 - Connection pool is full, discarding connection: matrix-synapse-the-old-gang.s3.amazonaws.com. Connection pool size: 10
```
Documentation for this provider covers how to set the thread pool, but not the connection pool.

Is this configurable through the yaml file? If not, should it be?

Or does this suggest there is something else broken with my setup?
